### ISSUE TITLE
<Battery />

### ISSUE THREAD

**Issue by hwclass** [jaredpalmer/react-fns#12]
Hey @jaredpalmer 

When I first saw your repo, I get excited. I was working on something sometime ago like [that](https://github.com/hwclass/react-battery). However, I would be happy to make my first contribution with a component containing battery functionality from browser api. Seems fair for you?

Thanks

Baris

**Comment by jaredpalmer** [comment]
Yeah

**Comment by jaredpalmer** [comment]
Go for it

**Comment by geirman** [comment]
Awesomeness! Here's another battery related library in case it's useful/inspirational
https://github.com/zanonnicola/react-device-battery

**Comment by hwclass** [comment]
Great! Starting... Thanks guys for feedback! 👍

**Comment by hwclass** [comment]
Hey folks, hi again,

After starting implementing the Battery Status feature, I have found something like [that](https://github.com/Microsoft/TSJS-lib-generator/pull/236). Maybe it should not add this as a component or not but it seems it is supported on only Chrome.

Any ideas?

Thanks

**Comment by geirman** [comment]
@hwclass bummer this has been flagged by the stale[bot], especially since it appears you just need a little guidance.

**Comment by jaredpalmer** [comment]
@geirman Flagged does not mean closed. My goal with stale bot was to let people raise their hand. 

With regards to this idea, it seems that there is no TS support and the API is deprecated?

**Comment by geirman** [comment]
@jaredpalmer Understood. I said flagged, but with the lack of activity it was also nearing the cliff's edge of being closed. I'm not sure if @hwclass still has interest in this after so much time though. I wish I had the time to look into it. Love this project overall.
