### ISSUE TITLE
Question: HoC with render prop vs function as child component

### ISSUE THREAD

**Issue by blakek** [jaredpalmer/react-fns#18]
First, this is an awesome library! 🎉  I'll definitely be using (and hopefully contributing) to this.

I just wanted to ask a question out of curiosity and learning.  Why did you choose a render prop that accepts a function over a function as a child component?  I do really like how using a render prop keeps things succinct.  I was just curious if there any benefits with going with one over the other?

Thanks in advance!

**Comment by jaredpalmer** [comment]
Just personal preference, I like `render` because I find it easier to refactor and read. I feel that I make more formatting mistakes with missed `{ }`  with `props.children`

**Comment by blakek** [comment]
Thanks for the answer!
