### ISSUE TITLE
I'd like to contribute but... Typescript

### ISSUE THREAD

**Issue by zanonnicola** [jaredpalmer/react-fns#28]
Would you accept a component written in just plain ES6 and not Typescript?
This is a really good project and I'd like to contribute to it. 

Keep up the good work anyway ⚡️

**Comment by prichodko** [comment]
I believe then it’s a great opportunity to learn new things! What do you find confusing about TypeScript, when looking on the other examples?

**Comment by zanonnicola** [comment]
You are right in saying that it's a good opportunity to learn new things but it's another "thing" I have to worry about instead of focusing on the component itself + more tooling is needed even if there are benefits of using Typescript of course. 

For example this: https://github.com/jaredpalmer/react-fns/blob/master/src/DeviceOrientation/DeviceOrientation.tsx#L12

For type checking why not just use `React’s PropTypes`?

**Comment by jaredpalmer** [comment]
TypeScript is far more expressive than PropTypes. It empowers me and my team to write safer, less buggy, and simpler code. It also let's us make sweeping API changes with confidence that our types stay sound.

**Comment by zanonnicola** [comment]
Fair enough! Thanks for taking the time to get back to me! 👍
