### ISSUE TITLE
Network's initial state doesn't reflect connection status

### ISSUE THREAD

**Issue by vhfmag** [jaredpalmer/react-fns#51]
Navigator's state is started as follows: `state: NetworkProps = { online: false }`. Given that the state is only changed inside `handleOnline` and `handleOffline`, the state only goes online after an `online` event.

For the component to work with SSR, I think it would be better to sync the state with `navigator.onLine` inside `componenDidMount` (something like `this.setState({ online: navigator && navigator.onLine || false })`). I will be submitting a PR.

**Comment by jaredpalmer** [comment]
It should instead Noop if navigator is undefined

**Comment by vhfmag** [comment]
What do you mean? Only set the state if navigator is defined?

**Comment by jaredpalmer** [comment]
Correct

**Comment by jaredpalmer** [comment]
There is no state on the server 😜

**Comment by vhfmag** [comment]
Oh, that makes sense. The PR I submitted only sets the state if navigator is defined (and does so inside `componentDidMount`), so everything should be fine. 😄
