### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by hukuuu** [jaredpalmer/react-fns#64]
Hi guys,

It will be really great if there is a CONTRIBUTING file with some explanations for the newbies

I cant get the project running. Tried the build and start script:
npm run build gave me lots of TS errors (error TS2307: Cannot find module 'react'.)
npm start: Error: spawn tsc-watch ENOENT

Im sure Im doing something wrong, but right now I feel a bit stuck.

**Comment by RusinovAnton** [comment]
Duplication of https://github.com/jaredpalmer/react-fns/issues/55
