### ISSUE TITLE
More side effect oriented APIs?

### ISSUE THREAD

**Issue by farskid** [jaredpalmer/react-fns#74]
I was working on an idea of declarative side effect management in React. Basically manage side effects as components such as Promises, Redirects, Title, MetaTags, WebWorkers, ...
I discussed the idea with Kent C. Dodds and he introduced me to this amazing library. He also suggested if we could ass these features to `react-fns`?
I like the idea. Are you having this in the roadmap so we could help make this happen?

I'd be happy to share what I've done so far and push this library forward.

**Comment by streamich** [comment]
How do you imagine `<WebWorkers>` component would work?

`<Title>` and `<MetaTags>` sound cool, I will definitely add those to [`libreact`](https://github.com/MailOnline/libreact).

I have `<Redirect>` component in progress, which will be handy to use together with `<Router>`.

And there is a simple [`<Resolve>`](https://github.com/MailOnline/libreact/blob/master/docs/en/Resolve.md) component that resolves promises.

**Comment by streamich** [comment]
Also, what would `<Title>` and `<MetaTags>` components do on server side?

**Comment by streamich** [comment]
I guess, on the server we would render into the `<head>` using [isomorphic portal](https://github.com/MichalZalecki/react-portal-universal) library.

**Comment by streamich** [comment]
Or maybe there could also be `<Html>`, `<Head>`, and `<Body>` utilities that would allow you to render the whole universal app:

```jsx
const App = () =>
  <Html>
    <Head>
      <Title>Hello world!</Title>
    </Head>
    <Body>
      <Router>
        <ThemeProvider>
          <div>{/* ... */}</div>
        <ThemeProvider>
      </Router>
    </Body>
  </Html
```

Or maybe all of that could be compressed into a single isomorphic `<Page>` component:

```jsx
const App = () =>
  <Page title='Hello world'>
      <Router>
        <ThemeProvider>
          <div>{/* ... */}</div>
        <ThemeProvider>
      </Router>
  </Page>
```

**Comment by streamich** [comment]
Found [`react-helmet`](https://github.com/nfl/react-helmet).

**Comment by farskid** [comment]
I assume <WebWorker /> would work as below:
```js
<WebWorker
  fn={someFuncHere}
  getWorkerInstance={worker => { this.worker =  worker}}
  onMessage={this.handleMessage}
/>
```

To achieve dynamic worker feature, we can use https://github.com/developit/workerize and transform `fn` prop to ESModule on the fly and let workerize handle the rest.

**Comment by farskid** [comment]
Other suggestion for side-effect components are:
* Interrval
* Timeout
* Log (multiple levels with custom adapter default fallback to `console`)
* Offline/Online
* Keyboard events

**Comment by streamich** [comment]
For Offline/Online you can use [`NetworkSensor`](https://github.com/MailOnline/libreact/blob/master/docs/en/NetworkSensor.md)

**Comment by farskid** [comment]
@streamich How do you think about the webworker proposal?
And you keep referencing libreact. is that library connected to react-fns or you're just referencing for more details?

**Comment by streamich** [comment]
I like the `<WebWorker>` proposal, I'm thinking there could also be a `<PostMessage>` component and `<WebWorker>` could use it internally.

I am currently working on libreact, I'm just referencing stuff that is already implemented.
