### ISSUE TITLE
v2

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/react-fns#89]

**Comment by jaredpalmer** [comment]
Hooks.

**Comment by rockmandash** [comment]
react-fns is the **_best repo_** to start supporting react hooks.

**Comment by jaredpalmer** [comment]
The plan is to use the-platform to keep this all backwards compat.

**Comment by artivilla** [comment]
Is that a new repo?

**Comment by jaredpalmer** [comment]
Yes.
